apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leetgaming

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - strimzi/
  - mongodb.yaml
  - deployment.yaml
  - web-frontend.yaml
  - observability/
