apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leetgaming

resources:
  - prometheus.yaml
  - prometheus-alerts.yaml
  - grafana.yaml
  - grafana-esports-dashboards.yaml
  - grafana-pyroscope-dashboards.yaml
  - grafana-replay-dashboards.yaml
  - pyroscope.yaml
